### PR TITLE
Change how serviceDetails locates package.json when hosted in iisnode on Windows

### LINKED ISSUE #60: serviceDetails cannot find package.json when hosted in iisnode on Windows
When hosted on Windows in IIS in iisnode, `process.mainModule` isn't the application. Instead iisnode's `interceptor.js` is started as main, which then loads the application. 

This means `process.mainModule.paths` cannot be used for where to look for `package.json`.
##### How to fix

If we're on iisnode we can use the fact that current working directory is set to the application's and we look for `package.json` there.

### PR DESCRIPTION
**Pull request by HCanber**
Fixes #60 **serviceDetails cannot find package.json when hosted in iisnode on Windows**

This PR fixes a problem in Windows.

When hosted on Windows in IIS in iisnode, `process.mainModule` isn't the application's main module. Instead iisnode's `interceptor.js` is started as main, which then loads the application. 

This means `process.mainModule.paths` cannot be used for where to look for `package.json`.

If we're on iisnode we can use the fact that current working directory is set to the application's and we look for `package.json` there.

Unfortunately, there is no safe way to determine if we're on iisnode. To make sure msb properly can detect that we're using iisnode the
any env var that starts with `"IISNODE_"` can be set, for example `IISNODE_HOSTED=true`
#### Code coverage for `serviceDetails.js`

This PR also improves the reported code coverage.
As the `serviceDetails` module was deleted from `require.cache` before each run, lab only reported the last run when doing code coverage analysis.

`serviceDetails.js` was refactored to provide a `_createForTest()` function that creates a new `serviceDetail` object without caching anything between
calls. 
`serviceDetails.js` still provides a default serviceDetail object for normal usage.

### CODE REVIEW

**Comment by HCanber** [comment]
Getting it to run on Travis was a struggle. Do we really need it to work on node 0.10 or can we move to node 4?

**Comment by jupiter** [comment]
@HCanber Good job on sorting out the coverage issues. 

There is currently a way to override the service name and version, `MSB_SERVICE_NAME` and `MSB_SERVICE_VERSION`, which are the only values that come from `package.json`. I would prefer not to add IIS-specific code unless it is absolutely neccesary. Adding the IIS-specific code means that we need to continue testing against IIS as well. However, if you really want the service name and version to be automatic based on the CWD, we could add an environment setting for this behaviour, e.g. `MSB_MAINMODULE_CWD=1`, which would simply search in CWD first for the package.json. Does the automation of service name and version make a big difference to your development flow?

**Comment by galkin** [comment]
I fully agree with jupiter `I would prefer not to add IIS-specific code unless it is absolutely neccesary`. So close.

**Comment by HCanber** [comment]
I also agree. 

However, we still need a way to provide the values from code, but we'll come back with a PR that's more to the point, and also not iis specific.

**Pull request closed without merging**
